# Generated by Django 3.0.8 on 2020-09-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_num', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(choices=[('UnderGraduate', 'UnderGraduate'), ('Graduate', 'Graduate'), ('PhD', 'PhD'), ('Academician', 'Academician')], default='UnderGraduate', max_length=256)),
                ('isIITR', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3)),
                ('institute', models.CharField(blank=True, max_length=256, null=True)),
                ('pay_num', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
